### PR TITLE
2

### PR DESCRIPTION
**Pull request by ghost**
#2 added license

### CODE REVIEW

**Comment by vutran** [comment]
Love the badge! Mind putting it on a new line? ([reference](https://github.com/vutran/dext)).

**Comment by ghost** [comment]
yeah, looks better

**Comment by vutran** [comment]
Sorry, can you rebase with just the badge. `LICENSE` file will be merged in via #4 since that was created first.

**Comment by ghost** [comment]
#2 Added some changes.

PS: i love badges too ;)

**Pull request closed without merging**
